In [2]:
from pathlib import Path
import glob
import numpy as np
import pandas as pd
import math
import folium
from IPython.display import display, IFrame
#import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
def readAllCSVFiles(folder_path):
    """
    Read all CSV files inside a folder into a Pandas Dataframe.
    Input: folder path
    Output: pandas dataframe
    """
    # 1. Define the path to your folder
    folder_path = folder_path + "/*.csv"
    # 2. Get list of files, read them, and concatenate vertically
    all_files = glob.glob(folder_path)
    
    df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=False)
    
    return df

In [19]:
#Read all the weather data from all the csv files in a Dataframe (df_weather)
df_weather = readAllCSVFiles("../Dataset/WeatherDataFromAcrossAlaska")
df_weather

,Date,Longitude,Latitude,Elevation,Max Temperature,Min Temperature,Precipitation,Wind,Relative Humidity,Solar
0,1/1/1979,-149.061996,69.158699,441,-4.936,-7.856,0.000000,4.356636,0.844523,0.000000
1,1/2/1979,-149.061996,69.158699,441,-4.201,-8.970,0.000000,5.970769,0.789418,0.000000
2,1/3/1979,-149.061996,69.158699,441,-4.651,-9.108,0.000000,4.126785,0.776695,0.000000
3,1/4/1979,-149.061996,69.158699,441,-7.666,-12.369,0.000000,2.739674,0.725190,0.000000
4,1/5/1979,-149.061996,69.158699,441,-7.498,-11.106,0.000000,3.364679,0.736841,0.000000
...,...,...,...,...,...,...,...,...,...,...
12982,7/27/2014,-149.061996,69.470901,172,12.949,-0.221,0.020599,4.300635,0.782682,24.381694
12983,7/28/2014,-149.061996,69.470901,172,6.281,3.180,1.000786,3.258264,0.897708,5.262818
12984,7/29/2014,-149.061996,69.470901,172,12.605,2.167,0.264359,2.775052,0.734158,16.473485
12985,7/30/2014,-149.061996,69.470901,172,16.161,-0.441,0.000000,3.331543,0.658231,23.576390
12986,7/31/2014,-149.061996,69.470901,172,19.509,8.539,0.020599,1.831378,0.546868,11.882375

In [22]:
#Read the wildfire data in a Dataframe (df_wildfire)
df_wildfire = readAllCSVFiles("../Dataset/WildFireDataFromAcrossAlaska")
df_wildfire

/tmp/ipykernel_1324267/1036471140.py:12: DtypeWarning: Columns (13,18,20,33,34,38,45,46,47,49,50,51,52,55,57,58,61,62,63,66,70,71,72,73,75,76,77,78,80,81,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=False)

,ID,NAME,FIRESEASON,FIRESEASONS,LASTUPDATETIME,MGMTORGID,MGMTOFFICEID,MGMTOPTIONID,PRESCRIBEDFIRE,LATITUDE,...,ISVALID,MERGEDINTO,MERGEDDATE,MERGED_REL_IRWINIRID,COMPLEX_REL_IRWINIRID,FIRECAUSE,ISQUARANTINED,CERTIFIED_IN_INFORM,WCE_INCIDENTID,MGMTOPTION_PROTDATE
0,70699,CRS GLENNALLEN FUELS BREAK RX,2024,2020 - 2029,1/2/2025 10:02:01,DOF,CRS,Critical,Y,62.091990,...,true,NaN,NaN,NaN,NaN,Undetermined,NaN,False,0868a5f7-fc18-4c0d-9eac-99ead46f8cb3,Critical
1,70698,CRS RX EFF FUELS SUPPORT,2024,2020 - 2029,1/2/2025 10:01:56,DOF,CRS,Critical,Y,62.091990,...,true,NaN,NaN,NaN,NaN,Undetermined,NaN,False,99a340a9-148c-4afa-8563-74d06260709f,Critical
2,70697,Eielson Avenue,2024,2020 - 2029,12/31/2024 09:01:55,DOF,DAS,Critical,N,64.072975,...,true,NaN,NaN,NaN,NaN,Human,False,True,b85c0a51-e7d3-4b44-a235-ec387686334d,Critical
3,70696,Denali Rx Fall,2024,2020 - 2029,10/31/2024 16:07:44,AFS,TAD,Critical,Y,63.733600,...,true,NaN,NaN,NaN,NaN,Human,NaN,False,f8e3c5a1-f639-43e7-a3a2-7a7886bee7a3,Critical
4,70693,Billie June Road,2024,2020 - 2029,10/26/2024 09:58:14,DOF,DAS,Critical,N,63.956644,...,true,NaN,NaN,NaN,NaN,Human,False,True,8b43d972-0552-4c61-922f-8f58365dd7b9,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35586,32040,Teklanika River,1939,1939 - 1949,7/7/2023 15:37:42,NaN,FAIRBANKS,Unplanned,N,64.433333,...,True,NaN,NaN,NaN,NaN,Human,False,False,NaN,NaN
35587,32038,Ship Creek,1939,1939 - 1949,7/7/2023 15:37:42,NaN,CHUGACH,Unplanned,N,61.233333,...,True,NaN,NaN,NaN,NaN,Human,False,False,NaN,NaN
35588,32037,Perhaps Creek,1939,1939 - 1949,7/7/2023 15:37:42,NaN,FAIRBANKS,Unplanned,N,65.266667,...,True,NaN,NaN,NaN,NaN,Undetermined,False,False,NaN,NaN
35589,32036,Palmer Butte,1939,1939 - 1949,5/4/2023 07:11:37,NaN,CHUGACH,Unplanned,N,61.550000,...,True,NaN,NaN,NaN,NaN,Human,False,False,NaN,NaN
35590,32028,Craemer,1939,1939 - 1949,7/7/2023 15:37:42,NaN,FAIRBANKS,Unplanned,N,64.866667,...,True,NaN,NaN,NaN,NaN,Human,False,False,NaN,NaN

In [44]:
#Get the unique locations in each of the tables
total_unique_location_weather = df_weather[['Latitude', 'Longitude']].drop_duplicates().shape[0]
print("Total number of unique weatherstation locations = " + str(total_unique_location_weather))

total_unique_location_wildfire = df_wildfire[['LATITUDE', 'LONGITUDE']].drop_duplicates().shape[0]
print("Total number of unique wildfire locations = " + str(total_unique_location_wildfire))

Total number of unique weatherstation locations = 35
Total number of unique wildfire locations = 29887

""" 
Notice the unique (longitude, latitude) combination in both the tables: Wildfire happened in so many different places. But, weather data has been collected only in a few places (Where the weather stations are installed). So, we need to align them spatially. This is called geospatial alignment 
"""

In [36]:
#Get the number of rows and columns in the dataframes
print("df_weather: " + " #columns = " + str(len(df_weather.columns)) + ", #rows = " + str(len(df_weather)) + " ( Narrow but long table ) ")
print("df_wildfire: " + "#columns = "  + str(len(df_wildfire.columns)) + ", #rows = " + str(len(df_wildfire)) + "  ( Wide but short table ) ")

df_weather:  #columns = 10, #rows = 454333 ( Narrow but long table )
df_wildfire: #columns = 84, #rows = 35591  ( Wide but short table )

"""
Notice the fact that wildfire is much rarer event (that happens once in a while) than a wether event (where the data is collected everyday of the year). We are calling each record an event. So, we need to align them temporally also.
"""

In [26]:
print("df_weather: " + " column names = ") 
print(df_weather.columns)
print ("df_weather: " + " column names = ")
print(df_wildfire.columns)

df_weather:  column names =
Index(['Date', 'Longitude', 'Latitude', 'Elevation', 'Max Temperature',
       'Min Temperature', 'Precipitation', 'Wind', 'Relative Humidity',
       'Solar'],
      dtype='object')
df_weather:  column names =
Index(['ID', 'NAME', 'FIRESEASON', 'FIRESEASONS', 'LASTUPDATETIME',
       'MGMTORGID', 'MGMTOFFICEID', 'MGMTOPTIONID', 'PRESCRIBEDFIRE',
       'LATITUDE', 'LONGITUDE', 'MAPNAME', 'MAPNUMBER', 'NEARESTWEATHERSTA',
       'ORIGINOWNERID', 'ORIGINADMINUNITID', 'DISCOVERYDATETIME',
       'DISCOVERYSIZE', 'IADATETIME', 'IASIZE', 'INITIALBEHAVIOR',
       'CONTROLDATETIME', 'OUTDATE', 'ESTIMATEDTOTALACRES', 'ACTUALTOTALACRES',
       'ESTIMATEDTOTALCOST', 'GENERALCAUSE', 'SPECIFICCAUSE', 'ORIGINSLOPE',
       'ORIGINASPECT', 'ORIGINELEVATION', 'ORIGINTOWNSHIP', 'ORIGINRANGE',
       'ORIGINSECTION', 'ORIGINQUARTER', 'ORIGINMERIDIAN',
       'STRUCTURESTHREATENED', 'STRUCTURESBURNED', 'PRIMARYFUELTYPE',
       'HARDCOPYREPORTAVAILABLE', 'TYPE1ASSIGNEDDATE', 'TYPE1RELEASEDDATE',
       'TYPE2ASSIGNEDDATE', 'TYPE2RELEASEDDATE', 'AFSNUMBER', 'DOFNUMBER',
       'USFSNUMBER', 'ADDITIONALNUMBER', 'FALSEALARM', 'FORCESITRPT',
       'FORCESITRPTSTATUS', 'RECORDNUMBER', 'COMPLEX', 'IMPORT_NOTES',
       'WFUFIRE', 'REPORTRECEIVEDDATE', 'ISCOMPLEX', 'CARRYOVER', 'STATEADSID',
       'ORIGINAL_LATITUDE', 'ORIGINAL_LONGITUDE', 'IRWINID',
       'SUPPRESSIONSTRATEGY', 'FIREMGMTCOMPLEXITY', 'ADSPERMISSIONSTATE',
       'OWNERKIND', 'FIRECODEREQUESTED', 'ISREIMBURSABLE', 'ISFSASSISTED',
       'ISTRESPASS', 'FIRECODENOTES', 'CONTAINMENTDATETIME', 'CONFLICTIRWINID',
       'COMPLEXPARENTIRWINID', 'ISVALID', 'MERGEDINTO', 'MERGEDDATE',
       'MERGED_REL_IRWINIRID', 'COMPLEX_REL_IRWINIRID', 'FIRECAUSE',
       'ISQUARANTINED', 'CERTIFIED_IN_INFORM', 'WCE_INCIDENTID',
       'MGMTOPTION_PROTDATE'],
      dtype='object')

""" 
Explanation of the columns can be found at this link: https://docs.google.com/presentation/d/1nzCLTu4hjsKXhTCGdvH5C1m8QdZzZOgu/edit?usp=sharing&ouid=104860836885149351076&rtpof=true&sd=true
"""

In [35]:
#Figure out what is the main reason of wildfire in Alaska
#The column named #FIRECAUSE in df_wildfire shows the cause of a fire.
print(df_wildfire['FIRECAUSE'].value_counts()) #This shows the sorted counts of each value in a specific column

#The column named #GENERALCAUSE in df_wildfire also shows the cause of a fire but in a more detailed fashion. 
print(df_wildfire['GENERALCAUSE'].value_counts())

FIRECAUSE
Human           20327
Natural         12222
False Alarm      1412
Undetermined     1068
Prescribed        287
?                 273
Rx?                 1
Name: count, dtype: int64
GENERALCAUSE
Human                                             8878
Lightning                                         7119
Natural                                           1485
False Alarm                                       1380
Debris Burning                                     936
Miscellaneous                                      891
Campfire                                           562
Equipment                                          293
Prescribed                                         223
Debris/Open Burning                                192
Incendiary                                         166
Lightning - WFU                                    145
Camping                                            139
Investigated but cause Undetermined                131
Smoking                                             99
Undetermined                                        95
Children                                            63
Debris and open burning                             62
Unknown                                             61
Other Human Cause                                   55
Recreation and ceremony                             38
Firearms and explosives use                         30
Under Investigation                                 24
Cause and Origin Not Identified                     22
Railroad                                            20
Other causes                                        18
Equipment and vehicle use                           17
Power generation / transmission / distribution      17
Coal Seam                                           16
Firearms/Weapons                                    14
Utilities                                           13
                                                    13
Children <12 yoa                                    12
Natural Out                                          5
Misuse of fire by a minor                            3
F/A                                                  2
Arson                                                2
Railroad operations and maintenance                  1
                                                     1
Juvenile 12-17 yoa                                   1
Equipment Use                                        1
Investigated but Undetermined                        1
Name: count, dtype: int64

In [ ]:
#